remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
collections:
  journal:
    output: true
    permalink: /:collection/:path/
include: ['_pages']
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      # _pages
  - scope:
      path: ""
      type: pages
      values:
          layout: single
          author_profile: true
    # _journal
  - scope:
      path: ""
      type: journal
    values:
        layout: single
        author_profile: false
        share: true
locale: "en-US"
title: "Refactored Train ğŸš‚"
name: "Refactored Train ğŸš‚"
title_separator: "ğŸ­ğŸŒˆâ˜€ï¸ğŸ¦„"
description: "My personal project"
url: "https://blaze349.github.io"
baseurl: "/refactored-train"
repository: "blaze349/refactored-train"
search: true
paginate: 10 # amount of posts to show
paginate_path: /list/page:num/
teaser: /assets/images/mandlebrot.jpg
